;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWGXYZ
;;Gauge: 15
x-stitch-number 68
;cast on skirt

inhook 1  
miss - f123 1 
tuck - f119 1 
miss - f115 1 
tuck - f111 1 
miss - f107 1 
tuck + f109 1 
tuck + f117 1 
tuck - b118 1 
tuck - b110 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
miss - f103 1 
tuck - f99 1 
miss - f95 1 
tuck - f91 1 
miss - f87 1 
tuck + f89 1 
tuck + f97 1 
tuck - b98 1 
tuck - b90 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
miss - f83 1 
tuck - f79 1 
miss - f75 1 
tuck - f71 1 
miss - f67 1 
tuck + f69 1 
tuck + f77 1 
tuck - b78 1 
tuck - b70 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
miss - f63 1 
tuck - f59 1 
miss - f55 1 
tuck - f51 1 
miss - f47 1 
tuck + f49 1 
tuck + f57 1 
tuck - b58 1 
tuck - b50 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
miss - f43 1 
tuck - f39 1 
miss - f35 1 
tuck - f31 1 
miss - f27 1 
tuck + f29 1 
tuck + f37 1 
tuck - b38 1 
tuck - b30 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
miss - f23 1 
tuck - f19 1 
miss - f15 1 
tuck - f11 1 
miss - f7 1 
tuck + f9 1 
tuck + f17 1 
tuck - b18 1 
tuck - b10 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
miss + f4 1 
tuck + b8 1 
miss + f12 1 
tuck + b16 1 
miss + f20 1 
miss + f23 1
xfer f18 b18 
xfer f10 b10 
xfer f9 b9 
xfer f17 b17 
miss + f24 1 
tuck + b28 1 
miss + f32 1 
tuck + b36 1 
miss + f40 1 
miss + f43 1
xfer f38 b38 
xfer f30 b30 
xfer f29 b29 
xfer f37 b37 
miss + f44 1 
tuck + b48 1 
miss + f52 1 
tuck + b56 1 
miss + f60 1 
miss + f63 1
xfer f58 b58 
xfer f50 b50 
xfer f49 b49 
xfer f57 b57 
miss + f64 1 
tuck + b68 1 
miss + f72 1 
tuck + b76 1 
miss + f80 1 
miss + f83 1
xfer f78 b78 
xfer f70 b70 
xfer f69 b69 
xfer f77 b77 
miss + f84 1 
tuck + b88 1 
miss + f92 1 
tuck + b96 1 
miss + f100 1 
miss + f103 1
xfer f98 b98 
xfer f90 b90 
xfer f89 b89 
xfer f97 b97 
miss + f104 1 
tuck + b108 1 
miss + f112 1 
tuck + b116 1 
miss + f120 1 
miss + f123 1
xfer f118 b118 
xfer f110 b110 
xfer f109 b109 
xfer f117 b117 
tuck - f123 1 
miss - f119 1 
tuck - f115 1 
miss - f111 1 
tuck - f107 1 
xfer b109 f109 
xfer b117 f117 
tuck + f105 1 
tuck + f113 1 
tuck - b114 1 
tuck - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
tuck - f103 1 
miss - f99 1 
tuck - f95 1 
miss - f91 1 
tuck - f87 1 
xfer b89 f89 
xfer b97 f97 
tuck + f85 1 
tuck + f93 1 
tuck - b94 1 
tuck - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
tuck - f83 1 
miss - f79 1 
tuck - f75 1 
miss - f71 1 
tuck - f67 1 
xfer b69 f69 
xfer b77 f77 
tuck + f65 1 
tuck + f73 1 
tuck - b74 1 
tuck - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
tuck - f63 1 
miss - f59 1 
tuck - f55 1 
miss - f51 1 
tuck - f47 1 
xfer b49 f49 
xfer b57 f57 
tuck + f45 1 
tuck + f53 1 
tuck - b54 1 
tuck - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
tuck - f43 1 
miss - f39 1 
tuck - f35 1 
miss - f31 1 
tuck - f27 1 
xfer b29 f29 
xfer b37 f37 
tuck + f25 1 
tuck + f33 1 
tuck - b34 1 
tuck - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
tuck - f23 1 
miss - f19 1 
tuck - f15 1 
miss - f11 1 
tuck - f7 1 
xfer b9 f9 
xfer b17 f17 
tuck + f5 1 
tuck + f13 1 
tuck - b14 1 
tuck - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
tuck + b4 1 
tuck + b12 1 
tuck + b20 1 
miss + f23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
tuck + b24 1 
tuck + b32 1 
tuck + b40 1 
miss + f43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
tuck + b44 1 
tuck + b52 1 
tuck + b60 1 
miss + f63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
tuck + b64 1 
tuck + b72 1 
tuck + b80 1 
miss + f83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
tuck + b84 1 
tuck + b92 1 
tuck + b100 1 
miss + f103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
tuck + b104 1 
tuck + b112 1 
tuck + b120 1 
miss + f123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
releasehook 1
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
knit - f123 1 
knit - f119 1 
knit - f115 1 
knit - f111 1 
knit - f107 1 
xfer b109 f109 
xfer b117 f117 
xfer b105 f105 
xfer b113 f113 
knit + f105 1 
knit + f109 1 
knit + f113 1 
knit + f117 1 
knit - b118 1 
knit - b114 1 
knit - b110 1 
knit - b106 1 
miss - f104 1
xfer b118 f118 
xfer b110 f110 
xfer b114 f114 
xfer b106 f106 
knit - f103 1 
knit - f99 1 
knit - f95 1 
knit - f91 1 
knit - f87 1 
xfer b89 f89 
xfer b97 f97 
xfer b85 f85 
xfer b93 f93 
knit + f85 1 
knit + f89 1 
knit + f93 1 
knit + f97 1 
knit - b98 1 
knit - b94 1 
knit - b90 1 
knit - b86 1 
miss - f84 1
xfer b98 f98 
xfer b90 f90 
xfer b94 f94 
xfer b86 f86 
knit - f83 1 
knit - f79 1 
knit - f75 1 
knit - f71 1 
knit - f67 1 
xfer b69 f69 
xfer b77 f77 
xfer b65 f65 
xfer b73 f73 
knit + f65 1 
knit + f69 1 
knit + f73 1 
knit + f77 1 
knit - b78 1 
knit - b74 1 
knit - b70 1 
knit - b66 1 
miss - f64 1
xfer b78 f78 
xfer b70 f70 
xfer b74 f74 
xfer b66 f66 
knit - f63 1 
knit - f59 1 
knit - f55 1 
knit - f51 1 
knit - f47 1 
xfer b49 f49 
xfer b57 f57 
xfer b45 f45 
xfer b53 f53 
knit + f45 1 
knit + f49 1 
knit + f53 1 
knit + f57 1 
knit - b58 1 
knit - b54 1 
knit - b50 1 
knit - b46 1 
miss - f44 1
xfer b58 f58 
xfer b50 f50 
xfer b54 f54 
xfer b46 f46 
knit - f43 1 
knit - f39 1 
knit - f35 1 
knit - f31 1 
knit - f27 1 
xfer b29 f29 
xfer b37 f37 
xfer b25 f25 
xfer b33 f33 
knit + f25 1 
knit + f29 1 
knit + f33 1 
knit + f37 1 
knit - b38 1 
knit - b34 1 
knit - b30 1 
knit - b26 1 
miss - f24 1
xfer b38 f38 
xfer b30 f30 
xfer b34 f34 
xfer b26 f26 
knit - f23 1 
knit - f19 1 
knit - f15 1 
knit - f11 1 
knit - f7 1 
xfer b9 f9 
xfer b17 f17 
xfer b5 f5 
xfer b13 f13 
knit + f5 1 
knit + f9 1 
knit + f13 1 
knit + f17 1 
knit - b18 1 
knit - b14 1 
knit - b10 1 
knit - b6 1 
miss - f4 1
xfer b18 f18 
xfer b10 f10 
xfer b14 f14 
xfer b6 f6 
knit + b4 1 
knit + b8 1 
knit + b12 1 
knit + b16 1 
knit + b20 1 
miss + b23 1
xfer f18 b18 
xfer f10 b10 
xfer f14 b14 
xfer f6 b6 
xfer f9 b9 
xfer f17 b17 
xfer f5 b5 
xfer f13 b13 
knit + b24 1 
knit + b28 1 
knit + b32 1 
knit + b36 1 
knit + b40 1 
miss + b43 1
xfer f38 b38 
xfer f30 b30 
xfer f34 b34 
xfer f26 b26 
xfer f29 b29 
xfer f37 b37 
xfer f25 b25 
xfer f33 b33 
knit + b44 1 
knit + b48 1 
knit + b52 1 
knit + b56 1 
knit + b60 1 
miss + b63 1
xfer f58 b58 
xfer f50 b50 
xfer f54 b54 
xfer f46 b46 
xfer f49 b49 
xfer f57 b57 
xfer f45 b45 
xfer f53 b53 
knit + b64 1 
knit + b68 1 
knit + b72 1 
knit + b76 1 
knit + b80 1 
miss + b83 1
xfer f78 b78 
xfer f70 b70 
xfer f74 b74 
xfer f66 b66 
xfer f69 b69 
xfer f77 b77 
xfer f65 b65 
xfer f73 b73 
knit + b84 1 
knit + b88 1 
knit + b92 1 
knit + b96 1 
knit + b100 1 
miss + b103 1
xfer f98 b98 
xfer f90 b90 
xfer f94 b94 
xfer f86 b86 
xfer f89 b89 
xfer f97 b97 
xfer f85 b85 
xfer f93 b93 
knit + b104 1 
knit + b108 1 
knit + b112 1 
knit + b116 1 
knit + b120 1 
miss + b123 1
xfer f118 b118 
xfer f110 b110 
xfer f114 b114 
xfer f106 b106 
xfer f109 b109 
xfer f117 b117 
xfer f105 b105 
xfer f113 b113 
rack 2
xfer b9 f11 
xfer b17 f19 
xfer b5 f7 
xfer b13 f15 
xfer b21 f23
xfer b29 f31 
xfer b37 f39 
xfer b25 f27 
xfer b33 f35 
xfer b41 f43
xfer b49 f51 
xfer b57 f59 
xfer b45 f47 
xfer b53 f55 
xfer b61 f63
xfer b69 f71 
xfer b77 f79 
xfer b65 f67 
xfer b73 f75 
xfer b81 f83
xfer b89 f91 
xfer b97 f99 
xfer b85 f87 
xfer b93 f95 
xfer b101 f103
xfer b109 f111 
xfer b117 f119 
xfer b105 f107 
xfer b113 f115 
xfer b121 f123
rack 1
xfer b18 f19 
xfer b10 f11 
xfer b14 f15 
xfer b6 f7 
xfer b22 f23
xfer b38 f39 
xfer b30 f31 
xfer b34 f35 
xfer b26 f27 
xfer b42 f43
xfer b58 f59 
xfer b50 f51 
xfer b54 f55 
xfer b46 f47 
xfer b62 f63
xfer b78 f79 
xfer b70 f71 
xfer b74 f75 
xfer b66 f67 
xfer b82 f83
xfer b98 f99 
xfer b90 f91 
xfer b94 f95 
xfer b86 f87 
xfer b102 f103
xfer b118 f119 
xfer b110 f111 
xfer b114 f115 
xfer b106 f107 
xfer b122 f123
rack 0
inhook 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
releasehook 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
knit - f123 2 
knit - f119 2 
knit - f115 2 
knit - f111 2 
knit - f107 2 
miss - f104 2
knit - f103 2 
knit - f99 2 
knit - f95 2 
knit - f91 2 
knit - f87 2 
miss - f84 2
knit - f83 2 
knit - f79 2 
knit - f75 2 
knit - f71 2 
knit - f67 2 
miss - f64 2
knit - f63 2 
knit - f59 2 
knit - f55 2 
knit - f51 2 
knit - f47 2 
miss - f44 2
knit - f43 2 
knit - f39 2 
knit - f35 2 
knit - f31 2 
knit - f27 2 
miss - f24 2
knit - f23 2 
knit - f19 2 
knit - f15 2 
knit - f11 2 
knit - f7 2 
miss - f4 2
knit + b4 2 
knit + b8 2 
knit + b12 2 
knit + b16 2 
knit + b20 2 
miss + f23 2
knit + b24 2 
knit + b28 2 
knit + b32 2 
knit + b36 2 
knit + b40 2 
miss + f43 2
knit + b44 2 
knit + b48 2 
knit + b52 2 
knit + b56 2 
knit + b60 2 
miss + f63 2
knit + b64 2 
knit + b68 2 
knit + b72 2 
knit + b76 2 
knit + b80 2 
miss + f83 2
knit + b84 2 
knit + b88 2 
knit + b92 2 
knit + b96 2 
knit + b100 2 
miss + f103 2
knit + b104 2 
knit + b108 2 
knit + b112 2 
knit + b116 2 
knit + b120 2 
miss + f123 2
outhook 1
outhook 2
drop f23  
drop f19  
drop f15  
drop f11  
drop f7  
drop b4  
drop b8  
drop b12  
drop b16  
drop b20  
drop f43  
drop f39  
drop f35  
drop f31  
drop f27  
drop b24  
drop b28  
drop b32  
drop b36  
drop b40  
drop f63  
drop f59  
drop f55  
drop f51  
drop f47  
drop b44  
drop b48  
drop b52  
drop b56  
drop b60  
drop f83  
drop f79  
drop f75  
drop f71  
drop f67  
drop b64  
drop b68  
drop b72  
drop b76  
drop b80  
drop f103  
drop f99  
drop f95  
drop f91  
drop f87  
drop b84  
drop b88  
drop b92  
drop b96  
drop b100  
drop f123  
drop f119  
drop f115  
drop f111  
drop f107  
drop b104  
drop b108  
drop b112  
drop b116  
drop b120  
