;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10

inhook 3 
tuck - f30 3
tuck - f29 3
tuck - f28 3
tuck - f27 3
tuck - f26 3
tuck - f25 3
tuck - f24 3
tuck - f23 3
tuck - f22 3
tuck - f21 3
tuck - f20 3
tuck - f19 3
tuck - f18 3
tuck - f17 3
tuck - f16 3
tuck - f15 3
tuck - f14 3
tuck - f13 3
tuck - f12 3
tuck - f11 3
tuck - f10 3
tuck - f9 3
tuck - f8 3
tuck - f7 3
tuck - f6 3
tuck - f5 3
tuck - f4 3
tuck - f3 3
tuck - f2 3
tuck - f1 3
releasehook 3
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
knit - b30 3 
knit - b29 3 
knit - b28 3 
knit - b27 3 
knit - b26 3 
knit - b25 3 
knit - b24 3 
knit - b23 3 
knit - b22 3 
knit - b21 3 
knit - b20 3 
knit - b19 3 
knit - b18 3 
knit - b17 3 
knit - b16 3 
knit - b15 3 
knit - b14 3 
knit - b13 3 
knit - b12 3 
knit - b11 3 
knit - b10 3 
knit - b9 3 
knit - b8 3 
knit - b7 3 
knit - b6 3 
knit - b5 3 
knit - b4 3 
knit - b3 3 
knit - b2 3 
knit - b1 3 
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
outhook 3
drop f1
drop f2
drop f3
drop f4
drop f5
drop f6
drop f7
drop f8
drop f9
drop f10
drop f11
drop f12
drop f13
drop f14
drop f15
drop f16
drop f17
drop f18
drop f19
drop f20
drop f21
drop f22
drop f23
drop f24
drop f25
drop f26
drop f27
drop f28
drop f29
drop f30
